### ISSUE TITLE
Cannot add the target: '_blank' parameter for links

### ISSUE THREAD

**Issue by Chewed2024** [enVolt/prosemirror-to-html#2]
Thank you for your good decision 👍

I studied the solution and the only thing that came to mind was to make a new Mark:
```
class Link extends Mark {
  matching() {
    return this.mark.type === 'link'
  }

  tag() {
    return [
      {
        tag: 'a',
        attrs: {
          href: this.mark.attrs.href,
          target: '_blank'
        }
      }
    ]
  }
}
```
And add it:
```
const renderer = new Renderer()
renderer.addMark(Link)
```

However, this label does not replace the one already added, but adds it to the Marks list.

I don't like that I can't pass target as a parameter when creating an instance of the class

**Comment by mariusgnicula** [comment]
Hey @Alehandro231 ! Don't know if you need this anymore, but I'll leave this here for others to find:
```import BaseLink from 'prosemirror-to-html-js/src/Marks/Link';
export default class Link extends BaseLink {
  tag () {
    return [
      {
        tag: "a",
        attrs: {
          href: this.mark.attrs.href,
          target: this.mark.attrs.target, // or directly '_blank'
        }
      }
    ]
  }
}
```
This extends the Link from **prosemirror-to-html-js**, so in your renderer you call this instead of the original Link.

**Comment by enVolt** [comment]
@Alehandro231 since the rendered iterates over various type of Nodes in form of array; it will not be possible to overwrite an existing class unless the mark type is different. 
Can you raise a PR for the same?
